namespace AeroHub.Contracts;

public sealed record RemoteIdDroneImportRecord(
    string? SerialNumber,
    string? OperatorId,
    string? OperationType,
    double? Latitude,
    double? Longitude,
    double? AltitudeGeodeticMeters,
    double? SpeedMetersPerSecond,
    double? DirectionDegrees,
    double? SeenSeconds,
    string? SourceApp,
    string? SourceFormat,
    DateTimeOffset? OriginalTimestampUtc,
    string? MessageType = null,
    string? UasId = null,
    string? UasIdType = null,
    string? UaType = null,
    int? OperatorIdType = null,
    string? OperationTypeSource = null,
    double? AltitudeBarometricMeters = null,
    double? HeightAboveGroundMeters = null,
    double? VerticalSpeedMetersPerSecond = null,
    string? AltitudeReference = null,
    double? HorizontalAccuracyMeters = null,
    double? VerticalAccuracyMeters = null,
    double? SpeedAccuracyMetersPerSecond = null,
    double? DirectionAccuracyDegrees = null,
    double? OperatorLatitude = null,
    double? OperatorLongitude = null,
    int? AreaCount = null,
    double? AreaRadiusMeters = null,
    double? AreaCeilingMeters = null,
    double? AreaFloorMeters = null,
    string? SelfIdText = null,
    string? AuthenticationStatus = null,
    bool? AuthenticationVerifiedBySource = null,
    string? Radio = null,
    double? Rssi = null,
    int? Channel = null,
    string? ReceiverId = null,
    string? SourceMac = null,
    string? RawPayload = null,
    string? ValidationStatus = null,
    IReadOnlyList<string>? ValidationWarnings = null,
    string? ObservationId = null);